[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
md5 = "0.7.0"
nom = "7.1.1"
regex = "1.7.0"
serde = "1.0.148"
serde_json = "1.0.89"
